yatube/about/urls.py
from django.urls import path
from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorPage.as_view(), name='about'),
    path('tech/', views.AboutTechPage.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views


app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group, name='group'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_details'),
    # Код ниже в процессе разработки
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
]

yatube/users/urls.py
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import LogoutView, LoginView
from django.urls import path
from django.urls import reverse_lazy

from . import views


app_name = 'users'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
    path(
      'logout/',
      LogoutView.as_view(template_name='users/logged_out.html'),
      name='logout'
    ),
    path('password_change/', auth_views.PasswordChangeView.as_view
         (template_name='users/password_change_form.html',
          success_url=reverse_lazy('users:password_change_done')),
         name='password_change_form'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view
         (template_name='users/password_change_done.html'),
         name='password_change_done'),
    path('password_reset/', auth_views.PasswordResetView.as_view
         (template_name='users/password_reset_form.html',
          email_template_name='users/password_reset_email.html',
          success_url=reverse_lazy('users:password_reset_done')),
         name='password_reset_form'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view
         (template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view
         (template_name='users/password_reset_confirm.html',
          success_url=reverse_lazy('users:password_reset_complete')),
         name='password_reset_confirm'),
    path('password_reset/complete/',
         auth_views.PasswordResetCompleteView.as_view
         (template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
    path('admin/', admin.site.urls),
]

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model


User = get_user_model()


class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
    )
    group = models.ForeignKey(
        'Group',
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
    )

    class Meta:
        ordering = ['-pub_date']

    def __str__(self):
        return self.text


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self):
        return self.title

yatube/users/models.py
from django.db import models


class Contact(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    subject = models.CharField(max_length=100)
    body = models.TextField()
    is_answered = models.BooleanField(default=False)

yatube/posts/forms.py
from django import forms
from .models import Post

"""Код ниже в процессе разработки."""


class PostEditionForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group')

        def clean_text(self):
            data = self.cleaned_data['text']
            if len(data) < 11:
                raise forms.ValidationError('Текст поста не может быть короче '
                                            '10 символов.')
            return data


class PostCreationForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group')

        def clean_text(self):
            data = self.cleaned_data['text']
            if len(data) < 11:
                raise forms.ValidationError('Текст поста не может быть короче '
                                            '10 символов.')
            return data

yatube/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model


User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

yatube/about/views.py
from django.views.generic.base import TemplateView


class AboutAuthorPage(TemplateView):
    template_name = 'about/author.html'


class AboutTechPage(TemplateView):
    template_name = 'about/tech.html'

yatube/posts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator

from .forms import PostEditionForm, PostCreationForm
from .models import Post, Group, User


def index(request):
    posts = Post.objects.select_related('author')
    paginator = Paginator(posts, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'posts/index.html', {
        'title': 'Последние обновления на сайте',
        'posts': posts,
        'page_obj': page_obj,
    })


def group(request, slug):
    group = get_object_or_404(Group, slug=slug)
    group_posts = group.posts.select_related('author')
    paginator = Paginator(group_posts, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'posts/group_post.html', {
        'title': 'Все записи сообщества',
        'group': group,
        'posts': group_posts,
        'page_obj': page_obj,
    })


def profile(request, username):
    author = get_object_or_404(User, username=username)
    post_list = author.posts.select_related('author')
    paginator = Paginator(post_list, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'author': author,
        'page_obj': page_obj,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    context = {
        'post': post,
    }
    return render(request, 'posts/post_details.html', context)


"""Код ниже в процессе разработки."""


def post_edit(request, post_id):
    if request.method == 'POST':
        form = PostEditionForm(request.POST)
        if not form.is_valid():
            form = PostEditionForm()
            return render(request, 'posts/index.html', {'form': form})
        text = form.cleaned_data['text']
        group = form.cleaned_data['group']
        return redirect('posts/post_details.html', id=post_id)

    form = PostEditionForm()
    return render(request, 'posts/index.html', {'form': form})

yatube/users/views.py
from django.shortcuts import render
from django.views.generic import CreateView
from django.urls import reverse_lazy

from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('posts:index')
    template_name = 'users/signup.html'

yatube/templates/about/author.html
{% extends 'base.html' %}
{% block title %}<title>Об авторе</title>{% endblock title %}
{% block content %}
<div class="container">
  <div class="row">
      <div class="col-md-12">
          <p>Данный проект был создан Иноземцевым Романом Сергеевичем, который заебался из-за заданий в тренажёре.</p>
          <p>Ну какого хера Яндекс, ЯНДЕКС! Не может себе позволить составить нормальную теоретическую базу???</p>
      </div>
  </div>
</div>
{% endblock content %}

yatube/templates/about/tech.html
{% extends 'base.html' %}
{% block title %}<title>Об авторе</title>{% endblock title %}
{% block content %}
<div class="container">
  <div class="row">
      <div class="col-md-12">
          <p>Данный проект был создан Иноземцевым Романом Сергеевичем на старой джанге 2.2.9</p>
          <p>Яндекс - компания от жадных для всех, кто купится.</p>
      </div>
  </div>
</div>
{% endblock content %}

yatube/templates/base.html
<!-- templates/base.html -->
<!DOCTYPE html>
{% load static %}
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{% static 'img/fav/favicon.ico' %}" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/fav/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/fav/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/fav/favicon-16x16.png' %}">
    <link rel="icon" type="image/png" sizes="192x192" href="{% static 'img/fav/android-chrome-192x192.png' %}">
    <link rel="icon" type="image/png" sizes="256x256" href="{% static 'img/fav/android-chrome-256x256.png' %}">
    <link rel="icon" type="image/png" sizes="150x150" href="{% static 'img/fav/mstile-150x150.png' %}">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    {% block title %}
        <title>
            Базовый заголовок
        </title>
    {% endblock title %}
  </head>
  <body>
    <header>
        {% include 'includes/header.html' %}
    </header>
    <main>
        {% block content %}
            Контент не подвезли :(
        {% endblock %}
    </main>
    <footer>
        {% include 'includes/footer.html' %}
    </footer>
  </body>
</html>

yatube/templates/includes/footer.html
<footer class="border-top text-center py-3">
    <p>© {{ year }} Copyright <span style="color:red">Ya</span>tube and <span style="color:red">k</span>92</p>
</footer>

yatube/templates/includes/header.html
{% load static %}
<nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
        <a class="navbar-brand" href="{% url 'posts:index' %}">
            <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
            <span style="color:red">Ya</span>tube
            {% if user.is_authenticated %}
                <a href="{% url 'posts:profile' user.username %}">Мой профиль</a>
                <a href="{% url 'users:logout' %}">Выйти</a>
            {% else %}
                <a href="{% url 'users:login' %}">Войти</a>
                <a href="{% url 'users:signup' %}">Регистрация</a>
            {% endif %}
        </a>
    </div>
</nav>

yatube/templates/posts/group_post.html
{% extends 'base.html' %}
{% block title %}<title>{{ group.title }}</title>{% endblock title %}
{% block content %}
    <div class="container py-5">
        <h1>Все записи группы {{ group }}</h1>
        <br>
        {% for post in page_obj %}
            <article>
                <ul>
                    <li>
                        Автор: <a
                            href="{% url 'posts:profile' post.author.username %}">{{ post.author.get_full_name }}</a>
                    </li>
                    <li>
                        Дата публикации: {{ post.pub_date|date:"d E Y" }}
                    </li>
                </ul>
                <p>
                    {{ post.text }}
                </p>
                <a href="{% url 'posts:post_details' post.id %}">Подробная информация</a>
            </article>
            {% if not forloop.last %}
                <hr>{% endif %}
        {% endfor %}
        {% include 'posts/includes/paginator.html' %}
    </div>
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %}<title>Главная</title>{% endblock title %}
{% block content %}
    <div class="container py-5">
        <h1>Последние обновления на сайте</h1>
        {% for post in page_obj %}
            <article>
                <ul>
                    <li>
                        Автор: {{ post.author.get_full_name }}
                    </li>
                    <li>
                        Дата публикации: {{ post.pub_date|date:"d E Y" }}
                    </li>
                </ul>
                <p>
                    {{ post.text }}
                </p>
                {% if post.group %}
                    <a href="{% url 'posts:group' post.group.slug %}">Все записи сообщества {{ post.group }}</a>
                {% endif %}
            </article>
            {% if not forloop.last %}
                <hr>{% endif %}
        {% endfor %}
    {% include 'posts/includes/paginator.html' %}
    </div>
{% endblock %}

yatube/templates/posts/post_details.html
{% extends 'base.html' %}
{% block title %}<title>Пост {{ post.text|truncatechars:30 }}</title>{% endblock title %}
{% block content %}
    <div class="container py-5">
        <ul>
            <li>
                Автор: <a
                    href="{% url 'posts:profile' post.author.username %}">{{ post.author.get_full_name }}</a>
            </li>
            {% if post.group %}
                <li>
                Группа: <a href="{% url 'posts:group' post.group.slug %}">{{ post.group }}</a>
            {% endif %}
            <li>
                Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
            </li>
            <li>
                Всего постов автора: <span>{{ post.author.posts.count }}</span>
            </li>
            <li>
                <a href="{% url 'posts:profile' post.author.username %}">
                    Все посты пользователя
                </a>
            </li>
        </ul>
        <article>
            <p>
                {{ post.text }}
            </p>
        </article>
    </div>
{% endblock content %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block title %}<title>Профайл пользователя @{{ author.username }}</title>{% endblock title %}
{% block content %}
    <div class="container py-5">
        <h1>Все посты пользователя {{ author.get_full_name }} </h1>
        <h3>Всего постов: {{ author.posts.count }} </h3>
        <br>
        {% for post in page_obj %}
            <article>
                <ul>
                    {% if post.group %}
                        <li>
                            Группа: <a href="{% url 'posts:group' post.group.slug %}">{{ post.group }}</a>
                        </li>
                    {% endif %}
                    <li>
                        Дата публикации: {{ post.pub_date|date:"d E Y" }}
                    </li>
                </ul>
                <p>
                    {{ post.text }}
                </p>
                <a href="{% url 'posts:post_details' post.id %}">Подробная информация</a>
            </article>
            {% if not forloop.last %}
                <hr>{% endif %}
        {% endfor %}
        {% include 'posts/includes/paginator.html' %}
    </div>
{% endblock content %}

yatube/templates/users/login.html
{% extends "base.html" %}
{% block title %}Войти{% endblock %}
{% block content %}
    {% load user_filters %}
    <div class="row justify-content-center">
        <div class="col-md-8 p-5">
            <div class="card">
                <div class="card-header">
                    Войти на сайт
                </div>
                <div class="card-body">
                    {% if form.errors %}
                        {% for field in form %}
                            {% for error in field.errors %}
                                <div class="alert alert-danger">
                                    {{ error|escape }}
                                </div>
                            {% endfor %}
                        {% endfor %}
                        {% for error in form.non_field_errors %}
                            <div class="alert alert-danger">
                                {{ error|escape }}
                            </div>
                        {% endfor %}
                    {% endif %}

                    <form method="post"
                            {% if action_url %}
                          action="{% url action_url %}"
                            {% endif %}
                    >
                        {% csrf_token %}

                        {% for field in form %}
                            <div class="form-group row my-3"
                                    {% if field.field.required %}
                                 aria-required="true"
                                    {% else %}
                                 aria-required="false"
                                    {% endif %}
                            >
                                <label for="{{ field.id_for_label }}">
                                    {{ field.label }}
                                    {% if field.field.required %}
                                        <span class="required text-danger">*</span>
                                    {% endif %}
                                </label>
                                <div>
                                    {{ field|addclass:'form-control' }}
                                    {% if field.help_text %}
                                        <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                                            {{ field.help_text|safe }}
                                        </small>
                                    {% endif %}
                                </div>
                            </div>
                        {% endfor %}
                        <div class="col-md-6 offset-md-4">
                            <button type="submit" class="btn btn-primary">
                                Войти
                            </button>
                            <a href="{% url 'users:password_reset_form' %}" class="btn btn-link">
                                Забыли пароль?
                            </a>
                        </div>
                    </form>
                </div> <!-- card body -->
            </div> <!-- card -->
        </div> <!-- col -->
    </div> <!-- row -->
{% endblock content %}

yatube/templates/users/password_change_form.html
{% extends 'base.html' %}
{% block title %}<title>Изменение пароля</title>{% endblock title %}
{% block content %}
    <div class="container py-5">
        <div class="row justify-content-center">
            <div class="col-md-8 p-5">
                <div class="card">
                    <div class="card-header">
                        Изменить пароль
                    </div>
                    <div class="card-body">
                        <form method="post" action="{% url 'users:password_change_form' %}">
                            {% csrf_token %}
                            <div class="form-group row my-3 p-3">
                                <label for="id_old_password">
                                    Старый пароль
                                    <span class="required text-danger">*</span>
                                </label>
                                <input type="password" name="old_password" autofocus class="form-control" required
                                       id="id_old_password">
                            </div>
                            <div class="form-group row my-3 p-3">
                                <label for="id_new_password1">
                                    Новый пароль
                                    <span class="required text-danger">*</span>
                                </label>
                                <input type="password" name="new_password1" class="form-control" required
                                       id="id_new_password1">
                                <small id="id_new_password1-help" class="form-text text-muted">
                                    <ul>
                                        <li>Ваш пароль не должен совпадать с вашим именем или другой персональной
                                            информацией или быть слишком похожим на неё.
                                        </li>
                                        <li>Ваш пароль должен содержать как минимум 8 символов.</li>
                                        <li>Ваш пароль не может быть одним из широко распространённых паролей.</li>
                                        <li>Ваш пароль не может состоять только из цифр.</li>
                                    </ul>
                                </small>
                            </div>
                            <div class="form-group row my-3 p-3">
                                <label for="id_new_password2">
                                    Подтверждение нового пароля
                                    <span class="required text-danger">*</span>
                                </label>
                                <input type="password" name="new_password2" class="form-control" required
                                       id="id_new_password2">
                            </div>
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    Изменить пароль
                                </button>
                            </div>
                        </form>
                    </div> <!-- card body -->
                </div> <!-- card -->
            </div> <!-- col -->
        </div> <!-- row -->
    </div>
{% endblock content %}

yatube/templates/users/password_reset_complete.html
{% extends 'base.html' %}
{% block title %}<title>Сброс пароля прошёл успешно</title>{% endblock title %}
{% block content %}
    <div class="container py-5">
        <div class="row justify-content-center">
            <div class="col-md-8 p-5">
                <div class="card">
                    <div class="card-header">
                        Восстановление пароля завершено
                    </div>
                    <div class="card-body">
                        <p>Ваш пароль был сохранен. Используйте его для входа</p>
                        <a href="{% url 'users:login' %}">Войти</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

yatube/templates/users/password_reset_confirm.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% block title %}<title>Новый пароль</title>{% endblock title %}
{% block content %}
    <div class="container py-5">
        <div class="row justify-content-center">
            <div class="col-md-8 p-5">
                <div class="card">
                    <div class="card-header">
                        Введите новый пароль
                    </div>
                    <div class="card-body">
                        <form method="post"
                              action="{% url 'users:password_reset_confirm' uidb64='uidb64' token='token' %}">
                            {% csrf_token %}
                            {#                  <input type="hidden" name="csrfmiddlewaretoken" value="">#}
                            <div class="form-group row my-3 p-3">
                                <label for="id_new_password1">
                                    Новый пароль
                                    <span class="required text-danger">*</span>
                                </label>
                                <input type="password" name="new_password1" class="form-control" required
                                       id="id_new_password1">
                                <small id="id_new_password1-help" class="form-text text-muted">
                                    <ul>
                                        <li>Ваш пароль не должен совпадать с вашим именем или другой персональной
                                            информацией или быть слишком похожим на неё.
                                        </li>
                                        <li>Ваш пароль должен содержать как минимум 8 символов.</li>
                                        <li>Ваш пароль не может быть одним из широко распространённых паролей.</li>
                                        <li>Ваш пароль не может состоять только из цифр.</li>
                                    </ul>
                                </small>
                            </div>
                            <div class="form-group row my-3 p-3">
                                <label for="id_new_password2">
                                    Подтверждение нового пароля
                                    <span class="required text-danger">*</span>
                                </label>
                                <input type="password" name="new_password2" class="form-control" required
                                       id="id_new_password2">
                            </div>
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    Назначить новый пароль
                                </button>
                            </div>
                        </form>
                    </div> <!-- card body -->
                </div> <!-- card -->
            </div> <!-- col -->
        </div> <!-- row -->
        <!-- если использована неправильная ссылка -->
        <div class="row justify-content-center">
            <div class="col-md-8 p-5">
                <div class="card">
                    <div class="card-header">
                        Ошибка
                    </div>
                    <div class="card-body">
                        <p>Ссылка сброса пароля содержит ошибку или устарела.</p>
                    </div> <!-- card body -->
                </div> <!-- card -->
            </div> <!-- col -->
        </div> <!-- row -->
        <!-- конец если использована неправильная ссылка -->
    </div>
{% endblock content %}

yatube/templates/users/password_reset_email.html
{% autoescape off %}
Вы получили это письмо, потому что вы (или кто-то другой) запросили восстановление пароля от учётной записи на сайте Yatube.project, которая связана с этим адресом электронной почты.

Пожалуйста, перейдите на эту страницу и введите новый пароль:
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uid token %}
{% endblock %}
Ваше имя пользователя (на случай, если вы его забыли): {{ user.username }}

Спасибо, что используете наш сайт!

Команда сайта Yatube.project

{% endautoescape %}

yatube/templates/users/password_reset_form.html
{% extends 'base.html' %}
{% block title %}<title>Сброс пароля</title>{% endblock title %}
{% block content %}
    <div class="container py-5">
        <div class="row justify-content-center">
            <div class="col-md-8 p-5">
                <div class="card">
                    <div class="card-header">
                        Чтобы сбросить старый пароль — введите адрес электронной почты, под которым вы регистрировались
                    </div>
                    <div class="card-body">
                        <form method="post" action="{% url 'users:password_reset_form' %}">
                            {% csrf_token %}
                            <div class="form-group row my-3 p-3">
                                <label for="id_email">
                                    Адрес электронной почты
                                    <span class="required text-danger">*</span>
                                </label>
                                <input type="email" name="email" maxlength="254" class="form-control" required
                                       id="id_email">
                            </div>
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    Сбросить пароль
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

yatube/templates/users/signup.html
{% extends "base.html" %}
{% block title %}Зарегистрироваться{% endblock %}
{% block content %}
    <div class="row justify-content-center">
        <div class="col-md-8 p-5">
            <div class="card">
                <div class="card-header">Зарегистрироваться</div>
                <div class="card-body">
                    {% load user_filters %}
                    {% if form.errors %}
                        {% for field in form %}
                            {% for error in field.errors %}
                                <div class="alert alert-danger">
                                    {{ error|escape }}
                                </div>
                            {% endfor %}
                        {% endfor %}
                        {% for error in form.non_field_errors %}
                            <div class="alert alert-danger">
                                {{ error|escape }}
                            </div>
                        {% endfor %}
                    {% endif %}

                    <form method="post" action="{% url 'users:signup' %}">
                        {% csrf_token %}

                        {% for field in form %}
                            <div class="form-group row my-3">
                                <label for="{{ field.id_for_label }}">
                                    {{ field.label }}
                                    {% if field.field.required %}
                                        <span class="required text-danger">*</span>
                                    {% endif %}
                                </label>
                                {{ field|addclass:'form-control' }}
                                {% if field.help_text %}
                                    <small
                                            id="{{ field.id_for_label }}-help"
                                            class="form-text text-muted"
                                    >
                                        {{ field.help_text|safe }}
                                    </small>
                                {% endif %}
                            </div>
                        {% endfor %}
                        <div class="col-md-6 offset-md-4">
                            <button type="submit" class="btn btn-primary">
                                Зарегистрироваться
                            </button>
                        </div>
                    </form>
                </div>
            </div> <!-- card -->
        </div> <!-- col -->
    </div> <!-- row -->
{% endblock %}